### ISSUE TITLE
setting tftp_packages in host_vars is ignored

### ISSUE THREAD

**Issue by kostyrevaa** [bertvv/ansible-role-tftp#4]
Having tftp_packages set in vars/main.yml leads to inability to override those at host_vars level.

**Comment by bertvv** [comment]
It is my opinion that the package selection should not be overridden by the administrator. The only reason to change the selection is when the package names are different on another distro. However, at this time, only EL7 is supported.

The `tftp` (client) package is not needed, however, and I will remove it.

**Comment by kostyrevaa** [comment]
Okay. But when you'll remove it?

**Comment by kostyrevaa** [comment]
I mean I can do it right away 'cause I'm setting this thing up now

**Comment by bertvv** [comment]
Now ;-) I just released a new version (1.2.0) with the Foreman code you
contributed and an updated vars/main.yml.
